name: Checkov

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: /
          framework: terraform 
          output_format: sarif
          config_file: checkov.yml
